[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "guiml"
version = "0.0.1"
dependencies = [
    "pyyaml",
    "pyglet",
    "cairocffi",
    "pangocffi",
    "pangocairocffi",
]